# run once rake spec_prep
# run often (avoiding download) rake spec_standalone
fixtures:
  forge_modules:
      stdlib:
          repo: "puppetlabs/stdlib"
          ref: "4.3.2"
      apt: "puppetlabs/apt"
      concat: "puppetlabs/concat"
      java: "puppetlabs/java"
      mysql: "puppetlabs/mysql"
      wget: "maestrodev/wget"
      postgresql: "puppetlabs/postgresql"
      vcsrepo: "puppetlabs/vcsrepo"
      git: "puppetlabs/git"
      ssh: 'erwbgy/ssh'
  repositories:
    rsnapshot: "git://github.com/ngiger/puppet-rsnapshot.git"
    samba:     "git://github.com/ngiger/puppet-samba.git"
  symlinks:
    elexis: "#{source_dir}"
